#!/usr/bin/env bash
# Campaign Session Launcher for boxes-live
# Creates a tmux session with coordinated panes for text-based adventure campaigns

set -e

# Configuration
SESSION_NAME="${1:-adventure-campaign}"
CAMPAIGN_DIR="${CAMPAIGN_DIR:-$HOME/.boxes-live/campaigns}"
CANVAS_FILE="${CAMPAIGN_DIR}/${SESSION_NAME}/realm.txt"

# Colors for terminal output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Create campaign directory if it doesn't exist
mkdir -p "${CAMPAIGN_DIR}/${SESSION_NAME}"

echo -e "${GREEN}🚀 Launching Campaign Session: ${SESSION_NAME}${NC}"

# Check if session already exists
if tmux has-session -t "${SESSION_NAME}" 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Session '${SESSION_NAME}' already exists. Attaching...${NC}"
    tmux attach-session -t "${SESSION_NAME}"
    exit 0
fi

# Initialize realm canvas if it doesn't exist
if [ ! -f "${CANVAS_FILE}" ]; then
    echo -e "${BLUE}📝 Initializing realm canvas...${NC}"
    cat > "${CANVAS_FILE}" << 'EOF'
# Campaign Realm Canvas
# Generated by campaign-session.sh

WIDTH: 200.0
HEIGHT: 150.0

BOX: 10.0 10.0 40.0 12.0
TITLE: Campaign Overview
CONTENT:
Welcome to the Adventure Campaign!
This canvas tracks realm state,
entity positions, and narrative flow.

Use SIGUSR1 to sync state across panes.
Use SIGUSR2 for custom campaign events.
END

BOX: 60.0 10.0 35.0 10.0
TITLE: Active Entities
CONTENT:
Heroes: 4
NPCs: 12
Enemies: 8
Locations: 15
END

BOX: 10.0 30.0 45.0 15.0
TITLE: Current Scene
CONTENT:
Location: The Whispering Woods
Time: Evening, Day 3
Weather: Light rain
Mood: Tense

The party stands at a crossroads...
END

BOX: 65.0 30.0 40.0 12.0
TITLE: Quest Log
CONTENT:
[Active] Find the Lost Artifact
[Active] Rescue the Villagers
[Complete] Defeat the Bandit Leader
END

BOX: 10.0 55.0 50.0 18.0
TITLE: World Map
CONTENT:
    N
    |
W --+-- E
    |
    S

Whispering Woods (You are here)
├─ Ancient Temple (NE)
├─ Village of Thornhaven (W)
└─ Dark Caverns (S)
END

BOX: 70.0 55.0 35.0 14.0
TITLE: Party Status
CONTENT:
Aria (Warrior) - HP: 85/100
Thorne (Rogue) - HP: 60/70
Lyra (Mage) - HP: 50/65
Brom (Cleric) - HP: 75/80
END
EOF
fi

# Create tmux session with campaign layout
echo -e "${BLUE}🎭 Creating tmux session with campaign layout...${NC}"

# Create new session with first pane (realm visualization)
tmux new-session -d -s "${SESSION_NAME}" -n "campaign"

# Set window layout
tmux split-window -h -t "${SESSION_NAME}:0"
tmux split-window -v -t "${SESSION_NAME}:0.1"

# Adjust pane sizes (left: 60%, right-top: 40%, right-bottom: 40%)
tmux select-layout -t "${SESSION_NAME}:0" main-vertical

# Pane 0 (left): Realm Canvas (boxes-live visualization)
tmux send-keys -t "${SESSION_NAME}:0.0" "clear" C-m
tmux send-keys -t "${SESSION_NAME}:0.0" "echo -e '${BLUE}📊 REALM CANVAS${NC}'" C-m
tmux send-keys -t "${SESSION_NAME}:0.0" "echo 'Loading realm visualization...'" C-m
tmux send-keys -t "${SESSION_NAME}:0.0" "sleep 1" C-m
tmux send-keys -t "${SESSION_NAME}:0.0" "./boxes-live '${CANVAS_FILE}'" C-m

# Pane 1 (right-top): Narrative/GM Console
tmux send-keys -t "${SESSION_NAME}:0.1" "clear" C-m
tmux send-keys -t "${SESSION_NAME}:0.1" "echo -e '${GREEN}📖 NARRATIVE CONSOLE${NC}'" C-m
tmux send-keys -t "${SESSION_NAME}:0.1" "echo ''" C-m
tmux send-keys -t "${SESSION_NAME}:0.1" "cat << 'NARRATIVE'
Campaign Session: ${SESSION_NAME}
Canvas: ${CANVAS_FILE}

🎲 GM Commands:
  - Edit realm: vi ${CANVAS_FILE}
  - Sync canvas: pkill -SIGUSR1 boxes-live
  - Trigger event: pkill -SIGUSR2 boxes-live
  - Update entity: Use connectors (realm2canvas)

📝 Narrative Mode:
  Type your narration below. Changes to the canvas
  file will auto-sync to the visualization pane.

NARRATIVE" C-m

# Pane 2 (right-bottom): State Manager / Command Center
tmux send-keys -t "${SESSION_NAME}:0.2" "clear" C-m
tmux send-keys -t "${SESSION_NAME}:0.2" "echo -e '${YELLOW}⚙️  STATE MANAGER${NC}'" C-m
tmux send-keys -t "${SESSION_NAME}:0.2" "echo ''" C-m
tmux send-keys -t "${SESSION_NAME}:0.2" "cat << 'STATE'
Campaign State: Active
Session: ${SESSION_NAME}
Realm File: ${CANVAS_FILE}

🔧 Quick Actions:
  1. List entities:     ./connectors/boxes-cli list ${CANVAS_FILE}
  2. Add entity:        ./connectors/boxes-cli add ${CANVAS_FILE} [options]
  3. Update state:      Edit canvas and sync (SIGUSR1)
  4. Export state:      ./connectors/boxes-cli export ${CANVAS_FILE} --json

💾 Canvas Stats:
STATE" C-m
tmux send-keys -t "${SESSION_NAME}:0.2" "./connectors/boxes-cli stats '${CANVAS_FILE}' 2>/dev/null || echo 'Stats unavailable'" C-m

# Select the narrative pane by default
tmux select-pane -t "${SESSION_NAME}:0.1"

# Create a helper script for campaign commands
HELPER_SCRIPT="${CAMPAIGN_DIR}/${SESSION_NAME}/commands.sh"
cat > "${HELPER_SCRIPT}" << 'HELPER'
#!/usr/bin/env bash
# Campaign Helper Commands

CANVAS_FILE="${CANVAS_FILE}"
SESSION_NAME="${SESSION_NAME}"

# Sync canvas (reload in boxes-live)
sync_canvas() {
    pkill -SIGUSR1 boxes-live
    echo "✓ Canvas synced"
}

# Trigger campaign event
trigger_event() {
    pkill -SIGUSR2 boxes-live
    echo "✓ Event triggered"
}

# Add entity to canvas
add_entity() {
    local name="$1"
    local x="${2:-50}"
    local y="${3:-50}"
    ./connectors/boxes-cli add "${CANVAS_FILE}" \
        --x "$x" --y "$y" --width 25 --height 8 \
        --title "$name" --content "Entity: $name"
    sync_canvas
}

# Update entity position
move_entity() {
    local id="$1"
    local x="$2"
    local y="$3"
    ./connectors/boxes-cli update "${CANVAS_FILE}" "$id" --x "$x" --y "$y"
    sync_canvas
}

# Export campaign state
export_state() {
    ./connectors/boxes-cli export "${CANVAS_FILE}" --json
}

case "${1:-help}" in
    sync) sync_canvas ;;
    event) trigger_event ;;
    add) add_entity "$2" "$3" "$4" ;;
    move) move_entity "$2" "$3" "$4" ;;
    export) export_state ;;
    *)
        echo "Campaign Commands:"
        echo "  sync              - Sync canvas to visualization"
        echo "  event             - Trigger campaign event"
        echo "  add NAME [X Y]    - Add entity to realm"
        echo "  move ID X Y       - Move entity"
        echo "  export            - Export campaign state"
        ;;
esac
HELPER

chmod +x "${HELPER_SCRIPT}"

# Set environment variables in all panes
for pane in 0 1 2; do
    tmux send-keys -t "${SESSION_NAME}:0.${pane}" "export CANVAS_FILE='${CANVAS_FILE}'" C-m
    tmux send-keys -t "${SESSION_NAME}:0.${pane}" "export SESSION_NAME='${SESSION_NAME}'" C-m
    tmux send-keys -t "${SESSION_NAME}:0.${pane}" "export CAMPAIGN_HELPER='${HELPER_SCRIPT}'" C-m
done

echo -e "${GREEN}✓ Campaign session created!${NC}"
echo ""
echo -e "${BLUE}📌 Session Info:${NC}"
echo "  Name: ${SESSION_NAME}"
echo "  Canvas: ${CANVAS_FILE}"
echo "  Helper: ${HELPER_SCRIPT}"
echo ""
echo -e "${YELLOW}🎮 Controls:${NC}"
echo "  - Edit narrative in right-top pane"
echo "  - Run commands in right-bottom pane"
echo "  - Sync changes: source \$CAMPAIGN_HELPER sync"
echo "  - Detach: Ctrl+b, then d"
echo "  - Reattach: tmux attach -t ${SESSION_NAME}"
echo ""
echo -e "${GREEN}🚀 Attaching to session...${NC}"
sleep 2

# Attach to the session
tmux attach-session -t "${SESSION_NAME}"
